# Generated by Django 6.0.1 on 2026-06-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_is_verified_user_verification_code_topicfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
